#!/bin/bash

function buildScript()
{
    local scriptName=${1:-""}

    [[ -z "${scriptName}" ]] && return 1
    build/${scriptName}.sh

    return $?
}

#
#==================================================
#

cd ~/Development/ewsldc/ldc-framework/core

#
#==================================================
#

cd ../core

#build/dcore.sh
buildScript "dcore" ; [[ $? -eq 0 ]] || exit $?

#
#==================================================
#

cd ../library

#build/dlibrary.sh
buildScript "dlibrary" ; [[ $? -eq 0 ]] || exit $?

#
#==================================================
#

cd ../base

buildScript "dbase" ; [[ $? -eq 0 ]] || exit $?
buildScript "dperl" ; [[ $? -eq 0 ]] || exit $?
buildScript "dx11-base" ; [[ $? -eq 0 ]] || exit $?
buildScript "dx11-surface" ; [[ $? -eq 0 ]] || exit $?
buildScript "dx11-dev" ; [[ $? -eq 0 ]] || exit $?

#
cd ../stack

buildScript "dcc" ; [[ $? -eq 0 ]] || exit $?
buildScript "dcc-x11" ; [[ $? -eq 0 ]] || exit $?
buildScript "dgtk2" ; [[ $? -eq 0 ]] || exit $?
buildScript "dgtk3" ; [[ $? -eq 0 ]] || exit $?
buildScript "dgtk2-x11" ; [[ $? -eq 0 ]] || exit $?
buildScript "dgtk3-x11" ; [[ $? -eq 0 ]] || exit $?
buildScript "dqt4" ; [[ $? -eq 0 ]] || exit $?
buildScript "dqt4-x11" ; [[ $? -eq 0 ]] || exit $?

#
cd ../stack-dev

buildScript "dcc-dev" ; [[ $? -eq 0 ]] || exit $?
buildScript "dgtk3-dev" ; [[ $? -eq 0 ]] || exit $?
buildScript "dqt4-dev" ; [[ $? -eq 0 ]] || exit $?

#
cd ../stack-apps

buildScript "djre8-gtk2" ; [[ $? -eq 0 ]] || exit $?
buildScript "djdk8-gtk2" ; [[ $? -eq 0 ]] || exit $?
buildScript "djdk13-gtk3" ; [[ $? -eq 0 ]] || exit $?
buildScript "djdk13dev-gtk3" ; [[ $? -eq 0 ]] || exit $?
buildScript "dcpp-jdk13" ; [[ $? -eq 0 ]] || exit $?
buildScript "dfortran-jdk13" ; [[ $? -eq 0 ]] || exit $?
buildScript "dfortran-gtk2" ; [[ $? -eq 0 ]] || exit $?
buildScript "djs13-jdk13" ; [[ $? -eq 0 ]] || exit $?
buildScript "djs14-jdk13" ; [[ $? -eq 0 ]] || exit $?
buildScript "dphp5.6-jdk13" ; [[ $? -eq 0 ]] || exit $?
buildScript "dphp5.6-js14" ; [[ $? -eq 0 ]] || exit $?
buildScript "dqt4-jdk13dev" ; [[ $? -eq 0 ]] || exit $?

#
cd ../dialog

buildScript "dialog" ; [[ $? -eq 0 ]] || exit $?
buildScript "kaptain" ; [[ $? -eq 0 ]] || exit $?
buildScript "whiptail" ; [[ $? -eq 0 ]] || exit $?
buildScript "zenity" ; [[ $? -eq 0 ]] || exit $?

#
cd ../ck-library

buildScript "ck-library" ; [[ $? -eq 0 ]] || exit $?

#
cd ../ckaptain

buildScript "ckaptain" ; [[ $? -eq 0 ]] || exit $?

#
#========================
#

cd ~/Development/ewsldc/ldc-applications/browser

#
cd ../browser

buildScript "ffquantum" ; [[ $? -eq 0 ]] || exit $?
#buildScript "firefox" ; [[ $? -eq 0 ]] || exit $?
buildScript "firefox-esr" ; [[ $? -eq 0 ]] || exit $?
buildScript "netsurf" ; [[ $? -eq 0 ]] || exit $?
buildScript "palemoon" ; [[ $? -eq 0 ]] || exit $?
buildScript "waterfox-classic" ; [[ $? -eq 0 ]] || exit $?
buildScript "waterfox-current" ; [[ $? -eq 0 ]] || exit $?

#

cd ../console

buildScript "nano" ; [[ $? -eq 0 ]] || exit $?
buildScript "tumblr"

#

cd ../desktop

buildScript "dia" ; [[ $? -eq 0 ]] || exit $?
buildScript "gimp" ; [[ $? -eq 0 ]] || exit $?
buildScript "mousepad" ; [[ $? -eq 0 ]] || exit $?
buildScript "obs-studio" 
buildScript "ripme" ; [[ $? -eq 0 ]] || exit $?
buildScript "shotcut" ; [[ $? -eq 0 ]] || exit $?

#

cd ../eclipse

buildScript "cpp" ; [[ $? -eq 0 ]] || exit $?
buildScript "fortran" ; [[ $? -eq 0 ]] || exit $?
buildScript "java" ; [[ $? -eq 0 ]] || exit $?
buildScript "javascript" ; [[ $? -eq 0 ]] || exit $?
buildScript "php" ; [[ $? -eq 0 ]] || exit $?
buildScript "qt" ; [[ $? -eq 0 ]] || exit $?

#

cd ../games

buildScript "mahjongg" ; [[ $? -eq 0 ]] || exit $?
buildScript "sol" ; [[ $? -eq 0 ]] || exit $?

#

cd ../libre

buildScript "office" ; [[ $? -eq 0 ]] || exit $?
buildScript "office-jdk" ; [[ $? -eq 0 ]] || exit $?
