#!/bin/bash

function buildScript()
{
    local scriptName=${1:-""}

    [[ -z "${scriptName}" ]] && return 1
    build/${scriptName}.sh

    return $?
}

#
#==================================================
#

cd ~/Development/ewsldc/ldc-applications/libre

buildScript "office-jdk" ; [[ $? -eq 0 ]] || exit $?
