#!/bin/bash

function buildScript()
{
    local scriptName=${1:-""}

    [[ -z "${scriptName}" ]] && return 1
    build/${scriptName}.sh

    return $?
}

#
#==================================================
#

cd ~/Development/ewsldc/ldc-applications/desktop

#
#==================================================
#

buildScript "ripme" ; [[ $? -eq 0 ]] || exit $?
buildScript "shotcut" ; [[ $? -eq 0 ]] || exit $?

#

cd ../eclipse

buildScript "cpp" ; [[ $? -eq 0 ]] || exit $?
buildScript "fortran" ; [[ $? -eq 0 ]] || exit $?
buildScript "java" ; [[ $? -eq 0 ]] || exit $?
buildScript "javascript" ; [[ $? -eq 0 ]] || exit $?
buildScript "php" ; [[ $? -eq 0 ]] || exit $?
buildScript "qt" ; [[ $? -eq 0 ]] || exit $?

#

cd ../games

buildScript "mahjongg" ; [[ $? -eq 0 ]] || exit $?
buildScript "sol" ; [[ $? -eq 0 ]] || exit $?

#

cd ../libre

buildScript "office" ; [[ $? -eq 0 ]] || exit $?
buildScript "office-jdk" ; [[ $? -eq 0 ]] || exit $?
